### ISSUE TITLE
魅族note5 白名单无效

### ISSUE THREAD

**Issue by haiyang1994** [WanghongLin/CRomAppWhitelist#1]
魅族note5白名单无效
Intent mzIntent = new Intent();
mzIntent.setComponent(new 
    ComponentName("com.meizu.safe","com.meizu.safe.powerui.PowerAppPermissionActivity"));
mzIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
keepers.add(mzIntent);
你这个代码是在那个机型/系统上测试的。

note5设置后台受保护应该是这个
 Intent mzNote5Intent = new Intent();
            mzNote5Intent.setComponent(new ComponentName("com.meizu.safe", "com.meizu.safe.security.AppSecActivity"));
            mzNote5Intent.putExtra("packageName", activity.getPackageName());
            keepers.add(mzNote5Intent);

**Comment by WanghongLin** [comment]
好的，谢谢反馈。已经提交了修复。https://github.com/WanghongLin/CRomAppWhitelist/commit/e4e2b0960d132fdaa54c9b8c93b15cf6866f5514

我当时是在一台比较老的魅族机器上面测试的。`MX4`，当时还是在API 19的系统上面，现在这台`MX4`已经升级到了API 22了。

**Comment by drogbababa** [comment]
请问您知道魅族note5 的悬浮窗权限应该怎么申请嘛？网上的方法没有效果。

**Comment by WanghongLin** [comment]
@drogbababa 如今手头没有对应的魅族机器了，希望你已经找到了设置方法。
